@startuml
!pragma useVerticalSwimlanes false
partition User {
  start
  :Login;
  :Ajukan permohonan issuer;
}
partition Admin {
  :Review permohonan;
  :Approve/Reject;
}
partition User {
  if (Permohonan di-approve?) then (Ya)
    :Status menjadi Issuer;
  else (Tidak)
    :Tampil pesan gagal;
  endif
}
partition Issuer {
  :Upload template sertifikat;
  :Terbitkan sertifikat;
  stop
}
@enduml

@startuml
!pragma useVerticalSwimlanes false
partition User {
  start
  :Input CID/URL sertifikat;
}
partition System {
  :Download PDF dari IPFS;
  :Hitung hash file (keccak256);
  :Bandingkan hash file dengan hash di blockchain;
  if (Hash cocok) then (ya)
    :Sertifikat valid;
  else (tidak)
    :Sertifikat tidak valid;
  endif
  stop
}
@enduml 